language: python
python:
    - "3.6"
install:
    - "pip install pyflakes"
    - "pip install -r requirements.txt"
cache:
    - pip
script:
    - pyflakes setup.py pyhedrals/
notifications:
    - email: false
